### ISSUE TITLE
Missing Platform Icon

### ISSUE THREAD

**Issue by joshcampbell191** [antongale/arcade-exerion#1]
### Version (or build number)

0.1.1

### Steps to reproduce

It appears that the platform icon (exertion.bin) isn’t part of the release files. I noticed that a png exists in the pkg directory. 

### Actual Behavior

Platform image is missing.

**Comment by antongale** [comment]
Added exerion.bin to platform folder.

**Comment by joshcampbell191** [comment]
Looks like it’s missing from the latest release v0.1.4

update: looks like it’s still building and v0.1.5 will contain the new file.

**Comment by antongale** [comment]
Try now :)
