### ISSUE TITLE
ROMs configuration

### ISSUE THREAD

**Issue by guytzs** [antongale/arcade-exerion#5]
### Ask a question about the IP Core

Hello @antongale / @boogermann 

I'm not very familiar with open FPGA, so please excuse my ignorance if my question is silly.

I get that I have to get the ROMs for this core on my own because you can't provide it for obvious reasons but perhaps you can still give me some clues:
Are the ROMs that I'm supposed to provide on my own the same as the ones I would provide if I were using MAME?

we can easily get ROMs like the following from many websites:

```
$ unzip -l exeriont.zip 
Archive:  exeriont.zip
TORRENTZIPPED-DADEE449
  Length      Date    Time    Name
---------  ---------- -----   ----
    16384  12-24-1996 23:32   prom5.4p
     8192  12-24-1996 23:32   prom6.4s
---------                     -------
    24576                     2 files
$ unzip -l exerion.zip 
Archive:  exerion.zip
TORRENTZIPPED-13AEF9FC
  Length      Date    Time    Name
---------  ---------- -----   ----
     8192  12-24-1996 23:32   exerion.01
     8192  12-24-1996 23:32   exerion.02
     8192  12-24-1996 23:32   exerion.03
     8192  12-24-1996 23:32   exerion.04
     8192  12-24-1996 23:32   exerion.05
     8192  12-24-1996 23:32   exerion.06
     8192  12-24-1996 23:32   exerion.07
     8192  12-24-1996 23:32   exerion.08
     8192  12-24-1996 23:32   exerion.09
     8192  12-24-1996 23:32   exerion.10
     8192  12-24-1996 23:32   exerion.11
       32  12-24-1996 23:32   exerion.e1
      256  12-24-1996 23:32   exerion.h10
      256  12-24-1996 23:32   exerion.i3
      256  12-24-1996 23:32   exerion.i8
      256  12-24-1996 23:32   exerion.k4
---------                     -------
    91168                     16 files
$ 
```

Not sure this is what is expected for this core though.
If I copy those .zip files in `./Assets/exerion/common` or unzip them, I end up with the following error:

`Error in framework missing 'rom' id [1]`

If I try to rename exeriont.zip to exeriont.rom, no error but I end up with a black screen.

From what I understand, this core is expecting a file named "exeriont.rom" in `./Assets/exerion/common`, am I correct?

Thanks!

**Comment by antongale** [comment]
The ROMs are built with a tool called ORCA (https://github.com/opengateware/tools-orca) that builds the ROM file from dumps such as the one you list in your question.  If you are unfamiliar with these tools I suggest you use a downloader tool that will automatically grab the files you need (such as https://github.com/mattpannella/pocket-updater-utility).

**Comment by guytzs** [comment]
thanks @antongale i used the `pocket-updater-utility`, this works great!
